services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    restart: unless-stopped
    healthcheck:
      disable: false
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.services.immich.loadbalancer.server.port=2283
      # Web access, use Authentik
      - traefik.http.routers.immich.rule=Host(`immich.${TRAEFIK_DOMAIN:?}`)
      - traefik.http.routers.immich.entrypoints=https
      - traefik.http.routers.immich.tls=true
      - traefik.http.routers.immich.tls.certresolver=cloudflare
      - traefik.http.routers.immich.middlewares=authentik@file
      # App access, skip Authentik (/share for skipping auth for share links)
      - traefik.http.routers.immich-well-known.rule=Host(`immich.${TRAEFIK_DOMAIN:?}`) && PathPrefix(`/api`) || PathPrefix(`/auth`) || Path(`/.well-known/immich`) || PathPrefix(`/share`)
      - traefik.http.routers.immich-well-known.entrypoints=https
      - traefik.http.routers.immich-well-known.tls=true
      - traefik.http.routers.immich-well-known.tls.certresolver=cloudflare
      - traefik.http.routers.immich-well-known.service=immich
    networks:
      - immich
      - traefik
    ports:
      - 2283:2283
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      # - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - cache
      - db

  # immich-machine-learning:
  #   container_name: immich_machine_learning
  #   # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
  #   # Example tag: ${IMMICH_VERSION:-release}-cuda
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
  #   #   file: hwaccel.ml.yml
  #   #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
  #   volumes:
  #     - model-cache:/cache
  #   env_file:
  #     - .env
  #   restart: always
  #   healthcheck:
  #     disable: false

  cache:
    # image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    image: valkey/valkey:8.1.2-alpine
    container_name: immich-cache
    hostname: redis
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich
    volumes:
      - cache:/data

  db:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich-db
    hostname: database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB:?} -U $${POSTGRES_USER:?}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: 'HDD'
    networks:
        - immich
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      # - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - db:/var/lib/postgresql/data

networks:
  immich:
    name: immich
  traefik:
    external: true

volumes:
  cache:
    name: immich-cache
  db:
    name: immich-db
  # model-cache:
